// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x2CA5E6FD)]
    public class STU_2CA5E6FD : STU_74A3AEC7 {
        [STUField(0x056D3E39)]
        public STU_CACA2D30 m_056D3E39;

        [STUField(0xB44A42A0)]
        public Enums.STUEnum_E7FEC166 m_B44A42A0;
    }
}
