// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x801A7230)]
    public class STU_801A7230 : STU_B719E73A {
        [STUField(0x056D3E39)]
        public STU_CACA2D30 m_056D3E39;
    }
}
