// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0xAC923A77)]
    public class STU_AC923A77 : STU_12ED1E44 {
        [STUField(0x334938EC)]
        public STU_84DF0CBC m_334938EC;
    }
}
