// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0xF9F748C2)]
    public class STU_F9F748C2 : STU_12ED1E44 {
        [STUField(0xEEF46CEE)]
        public STU_416D9897 m_EEF46CEE;
    }
}
