// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0xB3467FB2)]
    public class STU_B3467FB2 : STU_F029B472 {
        [STUField(0xEEF46CEE)]
        public STU_9BDF539E m_EEF46CEE;
    }
}
