// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x835A7560)]
    public class STU_835A7560 : STU_0CF6650E {
        [STUField(0x08CACF3A)]
        public Enums.STUEnum_149525F6 m_08CACF3A;
    }
}
