// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x9CDCA964)]
    public class STU_9CDCA964 : STU_783B8A59 {
        [STUField(0xB3EB3E0F)]
        public STU_32C5CD78 m_B3EB3E0F;

        [STUField(0x76A93966)]
        public STU_769D90C4 m_76A93966;
    }
}
