// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x5C443BEB)]
    public class STU_5C443BEB : STU_1D421571 {
        [STUField(0xEEF46CEE)]
        public STU_74A3AEC7 m_EEF46CEE;
    }
}
