// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x8F93980B)]
    public class STU_8F93980B : STU_783B8A59 {
        [STUField(0x736FB3D1)]
        public STU_F029B472 m_736FB3D1;
    }
}
