// File auto generated by STUHashTool
using static STULib.Types.Generic.Common;

namespace STULib.Types.Statistics {
    [STU(0x9F0705DA)]
    public class STU_9F0705DA : STU_1D421571 {
        [STUField(0x334938EC)]
        public STU_B719E73A m_334938EC;
    }
}
